module Glare
  module UxMetrics
    module BrandScore
      class Parser
        CHOICE_KEYS: Array[String]
        attr_reader questions: Array[Hash[::Symbol | ::String, ::String | ::Float | ::Integer] | Array[::String | ::Float | ::Integer]]

        def initialize: (
          questions: Array[Hash[::Symbol | ::String, ::String | ::Float | ::Integer] | Array[::String | ::Float | ::Integer]],
        ) -> void

        def valid?: -> bool

        def parse: -> Result

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end
  end
end
