module Glare
  module UxMetrics
    module Frequency
      class Parser
        CHOICE_KEYS: Array[String]
        attr_reader choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]

        def initialize: (choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]) -> void

        def valid?: -> bool

        def parse: -> Result

        @result: Float
        def result: -> Float

        @threshold: String
        def threshold: -> String

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end
  end
end
