module Glare
  module UxMetrics
    class Error < StandardError
    end

    module Sentiment
      class Data
        CHOICE_KEYS: Array[String]
        attr_reader choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]

        def initialize: (choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]) -> void

        def valid?: -> bool

        def parse: -> Result

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end

    module Feeling
      class Data
        CHOICE_KEYS: Array[String]
        attr_reader choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]

        def initialize: (choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]) -> void

        def valid?: -> bool

        def parse: -> Result

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end

    module Expectations
      class Data
        CHOICE_KEYS: Array[String]
        SENTIMENT_KEYS: Array[String]
        attr_reader choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]
        attr_reader sentiment: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]

        def initialize: (
            choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer],
            sentiment: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]) -> void

        def valid?: -> bool

        def parse: -> Result

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end

    module Desirability
      class Data
        CHOICE_KEYS: Array[String]
        attr_reader questions: Array[Hash[::Symbol | ::String, ::String | ::Float | ::Integer]]

        def initialize: (
          questions: Array[Hash[::Symbol | ::String, ::String | ::Float | ::Integer]]
        ) -> void

        def valid?: -> bool

        def parse: (question_index: Integer)-> Result

        def calculate_question: (Hash[::Symbol | ::String, ::String | ::Float | ::Integer]) -> float

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end

    module PostTaskSatisfaction
      class Data
        CHOICE_KEYS: Array[String]
        attr_reader choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer]

        def initialize: (
          choices: Hash[::Symbol | ::String, ::String | ::Float | ::Integer],
        ) -> void

        def valid?: -> bool

        def parse: -> Result

        def calculate_question: (Hash[::Symbol | ::String, ::String | ::Float | ::Integer]) -> float

        class InvalidDataError < Error
          def correct_data: -> String
        end
      end
    end


    class Result
      attr_reader result: Float
      attr_reader label: String
      attr_reader threshold: String

      def initialize: (result: Float, label: String, threshold: String) -> void
    end

    VERSION: String
  end
end
